version: '2'
services:
    enterprisemarket-app:
        image: enterprisemarket
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://enterprisemarket-mysql:3306/enterprisemarket?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    enterprisemarket-mysql:
        extends:
            file: mysql.yml
            service: enterprisemarket-mysql
